<template><view class="page"><ProfitHeader @export="handleExport" /><view class="content"><view class="sum"><view class="s" @click="handleFilterChange('all')"><text>总收入</text><text>¥{{ dashboard?.summary?.totalIncome||0 }}</text></view><view class="s" @click="handleFilterChange('settled')"><text>已入账</text><text>¥{{ dashboard?.summary?.settledAmount||0 }}</text></view><view class="s" @click="handleFilterChange('pending')"><text>待结算</text><text>¥{{ dashboard?.summary?.pendingAmount||0 }}</text></view><view class="s" @click="handleFilterChange('abnormal')"><text>异常</text><text>¥{{ dashboard?.summary?.abnormalAmount||0 }}</text></view></view><scroll-view scroll-x class="rail"><view class="chips"><view class="chip" v-for="f in dashboard?.filters||[]" :key="f.key" :class="{active:activeFilter===f.key}" @click="handleFilterChange(f.key)">{{ f.label }}</view></view></scroll-view><view class="ranges"><view class="r" :class="{active:activeDateRange==='today'}" @click="handleDateRangeChange('today')">今日</view><view class="r" :class="{active:activeDateRange==='week'}" @click="handleDateRangeChange('week')">本周</view><view class="r" :class="{active:activeDateRange==='month'}" @click="handleDateRangeChange('month')">本月</view><view class="r" :class="{active:activeDateRange==='custom'}" @click="handleDateRangeChange('custom')">自定义</view></view><SkeletonBlock v-if="pageState==='skeleton'" :rows="6" /><PageState v-else-if="pageState==='error'" state="error" title="加载失败" description="请稍后重试" action-text="重试" @retry="reload" /><StateBlock v-else-if="pageState==='filtered-empty'" state="empty" title="暂无匹配流水" description="请切换筛选条件" /><view v-else class="list"><view class="item" v-for="t in filteredTransactions||[]" :key="t.id" @click="handleTransactionClick(t)"><view class="b"><text class="title">{{ t.title }}</text><text class="m">{{ t.sourceTypeText }} · {{ t.relatedName }}</text><text class="m">{{ t.time }} · {{ t.serialNo }}</text></view><view class="a"><text :class="{neg:t.amount<0}">{{ t.amount>0?'+':'' }}¥{{ t.amount }}</text><text class="st">{{ t.statusText }}</text></view></view></view><view class="load" v-if="hasMore||loadingMore" @click="loadMore"><LoadingDots v-if="loadingMore"/><text v-else>加载更多</text></view><view class="nomore" v-else>没有更多了</view></view></view></template>
<script setup>
import { onMounted } from 'vue'
import { useProfitDashboard } from '../../hooks/useProfitDashboard'
import ProfitHeader from './components/ProfitHeader.vue'
import SkeletonBlock from '../../components/state/SkeletonBlock.vue'
import PageState from '../../components/state/PageState.vue'
import StateBlock from '../../components/state/StateBlock.vue'
import LoadingDots from '../../components/state/LoadingDots.vue'
const { dashboard, activeFilter, activeDateRange, filteredTransactions, hasMore, loadingMore, pageState, reload, loadMore, handleFilterChange, handleDateRangeChange, handleTransactionClick, handleExport } = useProfitDashboard()
onMounted(reload)
</script>
<style scoped>.page{min-height:100vh;background:#f5f7fb}.content{padding:20rpx 24rpx;display:flex;flex-direction:column;gap:12rpx}.sum{display:grid;grid-template-columns:repeat(4,minmax(0,1fr));gap:8rpx;background:#fff7ea;border-radius:14rpx;padding:10rpx}.s{min-width:0;text-align:center;font-size:20rpx;color:#7d6340}.s text:last-child{display:block;font-size:26rpx;color:#172033;font-weight:700}.rail{width:100%}.chips{display:flex;gap:10rpx;white-space:nowrap}.chip{flex:0 0 auto;padding:10rpx 16rpx;border:1rpx solid #e4e9f2;background:#fff;border-radius:999rpx;font-size:22rpx;color:#5b6880}.chip.active{background:#245bff;border-color:#245bff;color:#fff}.ranges{display:flex;background:#edf1f8;border-radius:999rpx;padding:6rpx}.r{flex:1;text-align:center;padding:10rpx 0;border-radius:999rpx;color:#6d7890;font-size:22rpx}.r.active{background:#245bff;color:#fff}.list{background:#fff;border-radius:16rpx;padding:12rpx}.item{display:flex;justify-content:space-between;gap:10rpx;padding:12rpx 0;border-bottom:1rpx solid #eef2f8}.item:last-child{border-bottom:0}.title{font-size:25rpx;color:#172033;font-weight:600}.m{display:block;font-size:22rpx;color:#69758c;margin-top:3rpx}.a{display:flex;flex-direction:column;align-items:flex-end;gap:4rpx;font-size:24rpx;color:#245bff;font-weight:600}.neg{color:#ff4d4f}.st{font-size:20rpx;color:#7f8aa0}.load,.nomore{padding:14rpx 0;text-align:center;color:#245bff;font-size:24rpx}.nomore{color:#9aa6b8}</style>
