<template><view class="page"><FinanceHeader @profit="handleProfitClick" @export="handleExport" /><view class="content"><view class="sum"><text class="title">本月收益</text><text class="money">¥{{ dashboard?.summary?.monthlyProfit||0 }}</text><text class="trend">较上月 {{ dashboard?.summary?.trend }}</text><view class="row"><text>今日 ¥{{ dashboard?.summary?.todayProfit||0 }}</text><text>待结算 ¥{{ dashboard?.summary?.pendingSettlement||0 }}</text><text>已结算 ¥{{ dashboard?.summary?.settledAmount||0 }}</text></view></view><view class="panel"><text class="h">结算状态</text><view class="grid"><view v-for="s in dashboard?.settlementStatus||[]" :key="s.key" class="card" @click="handleSettlementChange(s.key)"><text>{{ s.label }}</text><text class="n">¥{{ s.amount }}</text><text class="c">{{ s.count }} 笔</text></view></view></view><view class="panel"><text class="h">收入来源</text><view v-for="s in dashboard?.incomeSources||[]" :key="s.key" class="row"><text>{{ s.label }}</text><text>¥{{ s.amount }} · {{ s.percent }}%</text></view></view><view class="panel"><text class="h">财务提醒</text><view v-for="a in dashboard?.alerts||[]" :key="a.id" class="row" @click="handleActionClick(a.path)"><text>{{ a.title }}</text><text class="link">查看</text></view></view><view class="panel"><text class="h">快捷操作</text><view class="qgrid"><view class="q" @click="handleActionClick('/pages/finance/profit')">收益明细</view><view class="q" @click="handleActionClick('/pages/tools/export')">数据导出</view><view class="q" @click="handleActionClick('/pages/tools/qrcode')">收款码</view><view class="q" @click="handleActionClick('/pages/tools/contract')">合同管理</view><view class="q" @click="handleActionClick('/pages/tools/service')">客服中心</view></view></view><view class="panel"><text class="h">最近流水</text><view v-for="t in filteredRecentTransactions||[]" :key="t.id" class="row" @click="handleTransactionClick(t)"><text>{{ t.title }}</text><text :class="{neg:t.amount<0}">{{ t.amount>0?'+':'' }}¥{{ t.amount }}</text></view><view class="more" @click="handleProfitClick">更多 ></view></view><SkeletonBlock v-if="pageState==='skeleton'" :rows="6" /><PageState v-else-if="pageState==='error'" state="error" title="加载失败" description="请稍后重试" action-text="重试" @retry="reload" /></view></view></template>
<script setup>
import { onMounted } from 'vue'
import { useFinanceDashboard } from '../../hooks/useFinanceDashboard'
import FinanceHeader from './components/FinanceHeader.vue'
import SkeletonBlock from '../../components/state/SkeletonBlock.vue'
import PageState from '../../components/state/PageState.vue'
const { dashboard, filteredRecentTransactions, pageState, reload, handleSettlementChange, handleActionClick, handleTransactionClick, handleProfitClick, handleExport } = useFinanceDashboard()
onMounted(reload)
</script>
<style scoped>.page{min-height:100vh;background:#f5f7fb}.content{padding:20rpx 24rpx;display:flex;flex-direction:column;gap:12rpx}.sum{background:linear-gradient(135deg,#ffe4b3,#ffd384);border-radius:18rpx;padding:16rpx;color:#6f4a12}.title{font-size:23rpx}.money{display:block;font-size:56rpx;font-weight:700;color:#3b2a09}.trend{display:block;font-size:22rpx;color:#2e7d32}.row{display:flex;justify-content:space-between;gap:10rpx;padding:10rpx 0;border-bottom:1rpx solid #eef2f8;font-size:23rpx}.row:last-child{border-bottom:0}.panel{background:#fff;border-radius:16rpx;padding:14rpx}.h{font-size:26rpx;font-weight:700;color:#172033}.grid{display:grid;grid-template-columns:repeat(2,minmax(0,1fr));gap:10rpx;margin-top:10rpx}.card{background:#f8faff;border:1rpx solid #edf1f8;border-radius:12rpx;padding:10rpx}.n{display:block;font-size:30rpx;font-weight:700;color:#172033}.c{font-size:21rpx;color:#69758c}.link{color:#245bff}.qgrid{display:grid;grid-template-columns:repeat(5,minmax(0,1fr));gap:8rpx;margin-top:10rpx}.q{padding:10rpx;text-align:center;background:#f1f5ff;border-radius:10rpx;color:#245bff;font-size:21rpx}.neg{color:#ff4d4f}.more{text-align:right;color:#245bff;font-size:22rpx;padding-top:8rpx}</style>
